// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbrwbrxpkrwkpxfytpmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNicndicnhwa3J3a3B4Znl0cG14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODMwODIsImV4cCI6MjA2MzE1OTA4Mn0.k5AtPfNtD5ElvqEFibie5cv-ip4Xp3KxX0EW9NNMZMA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);